export const testData: Record<string, number | string>[] = [
  {
    id: 1,
    name: 'test',
    url: 'http://test.com',
    description: 'test',
    language: 'typescript',
    stars: 1,
    forks: 1,
    created_at: '2020-01-01',
  },
  {
    id: 2,
    name: 'test2',
    url: 'http://test2.com',
    description: 'test2',
    language: 'typescript',
    stars: 2,
    forks: 2,
    created_at: '2020-01-01',
  },
  {
    id: 3,
    name: 'test3',
    url: 'http://test3.com',
    description: 'test3',
    language: 'typescript',
    stars: 3,
    forks: 3,
    created_at: '2020-01-01',
  },
  {
    id: 4,
    name: 'test4',
    url: 'http://test4.com',
    description: 'test4',
    language: 'typescript',
    stars: 4,
    forks: 4,
    created_at: '2020-01-01',
  },
  {
    id: 5,
    name: 'test5',
    url: 'http://test5.com',
    description: 'test5',
    language: 'typescript',
    stars: 5,
    forks: 5,
    created_at: '2020-01-01',
  },
];
